//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Background
{
	public virtual int color
	{
		get;
		set;
	}

    public virtual void Background()
    {
        color = 0;
    }

    public virtual void Background(int myColor)
    {
        this.color = myColor;
    }

	public virtual Background get()
	{
        return this;
	}

	public virtual void set(Background background)
	{
        background.color = this.color;
	}

}

