//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Icones
{
	public virtual string path
	{
		get;
		set;
	}

	public virtual int screenPosition
	{
		get;
		set;
	}

    public virtual Icones()
    {
        this.path = "";
        this.screenPosition = 0;
    }

    public virtual Icones(String myPath, int myScreenPosition)
    {
        this.path = myPath;
        this.screenPosition = myScreenPosition;
    }

	public virtual Icones get()
	{
        return this;
	}

	public virtual void run()
	{
        Unity.run(this.path);
	}

}

