//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Options
{
	public virtual int tableOption
	{
		get;
		set;
	}

	public virtual string textOption
	{
		get;
		set;
	}

	public virtual int changeColorBackground()
	{
		throw new System.NotImplementedException();
	}

	public virtual Options get()
	{
		throw new System.NotImplementedException();
	}

}

