//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Pointer
{
	public virtual int xPos
	{
		get;
		set;
	}

	public virtual int yPos
	{
		get;
		set;
	}

	public virtual bool lClic
	{
		get;
		set;
	}

	public virtual bool rClic
	{
		get;
		set;
	}

	public virtual Pointer get()
	{
		return(this);
	}

	public virtual void set(int myXPos, int myYPos, bool myLClic, bool myRClic)
	{
        this.xPos = myXPos;
        this.yPos = myYPos;
        this.rClic = myRClic;
        this.lClic = myLClic;
	}

}

