//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface Windows 
{
	void pointer(Pointer pointer);

	void showOptions(Options option);

	void runApp(Icones icone);

	void changeColor(Background background);

}

